FROM alpine:3.15.4

ENV TZ=Europe/Moscow

RUN echo '@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk -U upgrade && \
    apk -v add --no-cache tor@edgecommunity lyrebird@testing runuser && \
    rm -rf /var/cache/apk/*

COPY entrypoint.sh ./entrypoint.sh

EXPOSE 9050/tcp
ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]