FROM alpine:3.15.4

ENV TZ=Europe/Moscow

RUN echo '@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
    apk -U upgrade && \
    apk -v add --no-cache tor@edgecommunity lyrebird@testing curl runuser && \
    rm -rf /var/cache/apk/*

COPY entrypoint.sh ./entrypoint.sh

HEALTHCHECK --timeout=10s --start-period=60s \
CMD curl --fail --socks5-hostname 127.0.0.1:9050 -I -L 'https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/' || exit 1

EXPOSE 9050/tcp
ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]